### ISSUE TITLE
(To Do) Kicking Down Doors?

### ISSUE THREAD

**Issue by Vaygrim** [Vaygrim/wasted#5] opened 2018-02-05 02:34 UTC
Cannot open doors while holding a gun from Vic's Modern Warfare. Possible opportunity for a 'niche mod' that would let us bind a hotkey for kicking doors open?

**Comment by mallrat208** [comment] 2018-02-10 07:53
Alright, I've started a mod called CQC for just this reason. Currently it has two features. One is to let you open a door/gate/or trapdoor when a button press and the other is to increase the damage done to shields by weapons. The first feature is on by default and the second one can be turned on if needed, personally I think it is as shields provide way too much protection versus gunfire than one would expect.

**Comment by mallrat208** [comment] 2018-02-10 08:58
As an update to what CQC can do:
 - You can kick open Doors, Trapdoors, and Gates that extend the vanilla classes
   - Wooden Doors work by default
   - Metal Doors can be enabled by Config, this counts doors that have the Material type Iron
   - Optionally, you can set it to damage the player that kicks open a Metal Door as well as specify the amount
 - Optionally, Shields can take extra damage from Vic's Projectiles
   - Shields take a percentage of their total max durability of damage on it. If the Damage taken by the player is greater than the percentage of durability that would be lost, the shield instead takes that amount of damage up to a maximum of twice percentage specified in the config
     - For example, I've got Wooden Shields set to take 15% damage per hit of a Vic's Weapon. 
     - Wooden Shields have a max durability of 336. So each hit will reduce it's total durability will drop by 50 (15%, rounded down)
     -  If the weapon shot would do 60 damage, the Shield would instead take 60 points of damage.
     -  If the weapon shot would do 130 damage, the Shield would instead take 100 points of damage as it is beyond the 30% (15% * 2) Cap 


As an aside, the 15% damage per hit for Wooden Shields may be a bit high, I'm probably going to drop it to about 10%

**Comment by mallrat208** [comment] 2018-02-10 10:21
CQC is now available on Curseforge and the Curse Launcher, 
https://minecraft.curseforge.com/projects/cqc

**Comment by XEridaniTribalX** [comment] 2018-02-11 01:23
Well, we're removing Vic's Modern Warfare because of the issue causing people not to be able to log into servers, so I think we can close this issue for now.

**Comment by XEridaniTribalX** [comment] 2018-02-11 01:38
Confirmed by Preacher in Discord; we can open doors and chests while wielding TG2 weapons. So this is moot; gonna close it on up.

**Closed as completed by XEridaniTribalX** 2018-02-11 01:38 UTC
Labels: Suggestion
